window.DICT = {
  en: {
    "mast.tagline": "A platform for academic research",
    "mast.signin": "Sign in",
    "mast.signup": "Sign up",
    "folio.l": "Tesyra Press",
    "folio.c1": "<em>Vol. I</em> · Issue 01",
    "folio.c2": "Published from Santiago",
    "folio.r": "May MMXXVI",

    "hero.eyebrow": "A research platform for the long form",
    "hero.l1": "Be happy thinking.",
    "hero.l2": "Everything is there.",
    "hero.standfirst": "Tesyra walks with you from reading sources to writing the article — through five modules and a single, structured thought.",
    "hero.cta1": "Start free <span class=\"arrow\">→</span>",
    "hero.cta2": "Read the prospectus",
    "hero.gm1": "Plate 01 — The Spine",
    "hero.gm2": "After the outline",

    "demo.acc": "Plate 00 · In motion",
    "demo.runtime": "00:42 · silent loop",
    "demo.l1": "The platform,",
    "demo.l2": "in forty-two seconds.",
    "demo.corner": "Tesyra · Reel 01",
    "demo.cap": "From reading sources to writing the article — the five movements, threaded through one structured thought.",
    "demo.meta": "Recorded May MMXXVI",
    "demo.sound.off": "Sound off",
    "demo.sound.on": "Sound on",

    "g.label": "The Gap",
    "g.l1": "You read.",
    "g.l2": "You annotate. You think.",
    "g.l3": "And then it all",
    "g.l4": "slips away.",
    "g.p1": "Hundreds of sources. Scattered notes. Brilliant insights trapped inside PDFs and forgotten folders. <strong>The gap between reading and writing is where your best ideas are lost.</strong>",
    "g.p2": "When you sit down to write, you start by reconstructing what you already knew last Tuesday — instead of building on it.",
    "g.frag.h": "— A typical afternoon, in fragments",

    "m.label": "The Method",
    "m.display": "Five movements. <em>One thought.</em>",
    "m.lead": "Each module is shaped to its moment — and each opens into the next. Insights from your reading feed your dialogue; what you decide in dialogue assembles your outline; the outline becomes the writing.",
    "m.r.id": "The Reading",
    "m.r.name": "Sources, read closely.",
    "m.r.desc": "— analyse, annotate, interrogate",
    "m.r.body": "Upload papers and pull out thesis, structure, key moves. Talk to one document or to many at once. Import from Zotero. Every passage you mark becomes a candidate for the next stage.",
    "m.d.id": "The Discussion",
    "m.d.name": "Dialogue, not autocomplete.",
    "m.d.desc": "— challenge, follow-up, structure",
    "m.d.body": "A guided conversation that challenges your assumptions, asks follow-up questions, and produces a structured outline — not a transcript.",
    "m.o.id": "The Outline",
    "m.o.name": "The spine of your article.",
    "m.o.desc": "— sections, gaps, evidence",
    "m.o.body": "Insights find their subsection. Missing sources are flagged. The argumentative architecture takes shape without you assembling it by hand.",
    "m.l.id": "The Literature Review",
    "m.l.name": "References as a network.",
    "m.l.desc": "— citation, cluster, centrality",
    "m.l.body": "Your bibliography rendered as warp and weft — who cites whom, which sources cluster, which are central. Not a list. A field.",
    "m.w.id": "The Writing",
    "m.w.name": "The page, finally.",
    "m.w.desc": "— compose, edit, cite",
    "m.w.body": "An editor per subsection, with your insights and sources beside you. Editorial review, translation, and citation handling — APA, Chicago, OSCOLA, and more.",

    "c.label": "Crystallisations",
    "c.l1": "Your ideas",
    "c.l2": "deserve to survive.",
    "c.p1": "Every insight you have while reading or in dialogue — every theoretical tension, every methodological move, every gap — captured with one click, classified, and filed exactly where it belongs in your outline.",
    "c.p2": "By the time you write, the argument has already been laid down. You're not assembling — you're composing.",
    "c.t1.l": "Theoretical",     "c.t1.n": "A tension, a frame.",
    "c.t2.l": "Methodological",  "c.t2.n": "A way of looking.",
    "c.t3.l": "Empirical",       "c.t3.n": "A finding, a fact.",
    "c.t4.l": "Structural",      "c.t4.n": "A shape, a gap.",
    "c.cat.acc": "Acc. 0042 · Theoretical",
    "c.cat.date": "Filed Tue 03:42 AM",
    "c.cat.title": "Threshold ecologies and ambient commons",
    "c.cat.body": "&ldquo;Conventional commons frameworks falter where boundaries are diffuse — ambient noise, light spill, micro-climates being paradigmatic cases.&rdquo;",
    "c.cat.src": "Halbersohn · 2017 · p. 32",
    "c.cat.dest": "§2.1 Ambient thresholds as commons",

    "p.label": "Position",
    "p.q1": "AI Discussion,",
    "p.q2": "not AI writing.",
    "p.body": "This is not autocomplete for your thesis. The system challenges your assumptions, asks follow-up questions, and helps you think more clearly. You still write. The argument remains yours.",
    "p.them.h": "— Other tools",
    "p.them.1": "Generate paragraphs without telling you which sources back them.",
    "p.them.2": "Erase the trace of your reasoning.",
    "p.them.3": "Leave you with text you can't defend.",
    "p.them.4": "Every conversation starts from zero.",
    "p.us.h": "+ Tesyra",
    "p.us.1": "Crystallises the idea. Files it where it belongs.",
    "p.us.2": "Your argument takes shape as you build it — not after.",
    "p.us.3": "By the time you sit down to write, the structure already exists.",
    "p.us.4": "Every insight references its source and its subsection.",

    "a.label": "Access",
    "a.d1": "Every plan,",
    "a.d2": "every module.",
    "a.lead.1": "No feature gates. All the tools, from day one.",
    "a.lead.2": " The best model on every tier.",
    "a.h.col": "Plan",
    "a.t1.name": "Explorer", "a.t1.tag": "— for the first article",
    "a.t2.name": "Researcher", "a.t2.tag": "— for parallel projects",
    "a.t3.name": "Academic Pro", "a.t3.tag": "— for theses & books",
    "a.r.price": "Tariff",
    "a.t1.per": "forever",
    "a.t2.per": "/ month",
    "a.t3.per": "/ month",
    "a.r.credits": "Credits / month",
    "a.r.projects": "Active projects",
    "a.r.docs": "Documents per project",
    "a.r.conv": "Conversations per project",
    "a.r.outlines": "Outlines per project",
    "a.r.preassign": "Intelligent pre-assignment",
    "a.r.gaps": "Bibliographic gap detection",
    "a.r.briefing": "Daily briefing",
    "a.r.storage": "Storage",
    "a.r.included": "included", "a.r.included2": "included", "a.r.included3": "included",
    "a.r.included4": "included", "a.r.included5": "included", "a.r.included6": "included",
    "a.t1.cta": "Start free",
    "a.t2.cta": "Try 14 days",
    "a.t3.cta": "Get started",
    "a.note": "Prices in USD. Cancel anytime. Billing handled by Paddle (our merchant of record).",

    "end.l1": "Be happy thinking.",
    "end.l2": "Everything is there.",
    "end.sub": "Starting is free. No card required.",
    "end.cta1": "Start free <span class=\"arrow\">→</span>",
    "end.cta2": "Read the prospectus",

    "fc.about": "A research platform for academic researchers. From reading sources to writing the article — structured thinking, assisted.",
    "fc.product": "Product",
    "fc.method": "The Method",
    "fc.crystals": "Crystallisations",
    "fc.pricing": "Access",
    "fc.position": "Position",
    "fc.resources": "Resources",
    "fc.docs": "Documentation",
    "fc.changelog": "Changelog",
    "fc.support": "Support",
    "fc.company": "Company",
    "fc.about-us": "About",
    "fc.contact": "Contact",
    "fc.press": "Press",
    "fc.legal": "Legal",
    "fc.privacy": "Privacy",
    "fc.terms": "Terms",
    "fc.dpa": "Data processing",
    "fc.signoff": "Made with care for researchers"
  },

  es: {
    "mast.tagline": "Una plataforma para la investigación académica",
    "mast.signin": "Entrar",
    "mast.signup": "Crear cuenta",
    "folio.l": "Tesyra Press",
    "folio.c1": "<em>Vol. I</em> · Núm. 01",
    "folio.c2": "Publicado desde Santiago",
    "folio.r": "Mayo MMXXVI",

    "hero.eyebrow": "Una plataforma para la investigación de largo aliento",
    "hero.l1": "Disfruta pensar.",
    "hero.l2": "Todo está ahí.",
    "hero.standfirst": "Tesyra te acompaña desde la lectura de fuentes hasta la escritura del artículo — a través de cinco módulos y un solo pensamiento estructurado.",
    "hero.cta1": "Empezar gratis <span class=\"arrow\">→</span>",
    "hero.cta2": "Leer el prospecto",
    "hero.gm1": "Lámina 01 — La espina",
    "hero.gm2": "Tras la estructura",

    "demo.acc": "Lámina 00 · En movimiento",
    "demo.runtime": "00:42 · loop silencioso",
    "demo.l1": "La plataforma,",
    "demo.l2": "en cuarenta y dos segundos.",
    "demo.corner": "Tesyra · Reel 01",
    "demo.cap": "De la lectura de fuentes a la escritura del artículo — los cinco movimientos, hilados a un solo pensamiento estructurado.",
    "demo.meta": "Grabado mayo MMXXVI",
    "demo.sound.off": "Sin sonido",
    "demo.sound.on": "Con sonido",

    "g.label": "El hueco",
    "g.l1": "Lees.",
    "g.l2": "Anotas. Piensas.",
    "g.l3": "Y entonces todo",
    "g.l4": "se desvanece.",
    "g.p1": "Cientos de fuentes. Apuntes dispersos. Hallazgos brillantes atrapados en PDFs y carpetas olvidadas. <strong>El hueco entre leer y escribir es donde se pierden tus mejores ideas.</strong>",
    "g.p2": "Cuando te sientas a escribir, empiezas reconstruyendo lo que ya sabías el martes pasado — en lugar de partir desde ahí.",
    "g.frag.h": "— Una tarde típica, en fragmentos",

    "m.label": "El método",
    "m.display": "Cinco movimientos. <em>Un pensamiento.</em>",
    "m.lead": "Cada módulo está modelado a su momento — y cada uno se abre al siguiente. Los hallazgos de tu lectura alimentan tu diálogo; lo que decides en diálogo arma tu outline; el outline se vuelve escritura.",
    "m.r.id": "The Reading",
    "m.r.name": "Fuentes, leídas de cerca.",
    "m.r.desc": "— analizar, anotar, interrogar",
    "m.r.body": "Sube papers y extrae tesis, estructura y argumentos clave. Habla con un documento o con varios a la vez. Importa desde Zotero. Cada pasaje que marcas se vuelve candidato para la siguiente etapa.",
    "m.d.id": "The Discussion",
    "m.d.name": "Diálogo, no autocompletar.",
    "m.d.desc": "— desafío, seguimiento, estructura",
    "m.d.body": "Una conversación guiada que desafía tus supuestos, hace preguntas de seguimiento, y produce un outline estructurado — no un transcript.",
    "m.o.id": "The Outline",
    "m.o.name": "La espina de tu artículo.",
    "m.o.desc": "— secciones, huecos, evidencia",
    "m.o.body": "Los insights encuentran su subsección. Las fuentes faltantes se detectan. La arquitectura argumentativa toma forma sin que la armes a mano.",
    "m.l.id": "The Literature Review",
    "m.l.name": "Las referencias como red.",
    "m.l.desc": "— cita, clúster, centralidad",
    "m.l.body": "Tu bibliografía como urdimbre y trama — quién cita a quién, qué fuentes forman clúster, cuáles son centrales. No una lista. Un campo.",
    "m.w.id": "The Writing",
    "m.w.name": "La página, por fin.",
    "m.w.desc": "— componer, editar, citar",
    "m.w.body": "Un editor por subsección, con tus insights y fuentes al lado. Revisión editorial, traducción, gestión de citas — APA, Chicago, OSCOLA y más.",

    "c.label": "Cristalizaciones",
    "c.l1": "Tus ideas",
    "c.l2": "merecen sobrevivir.",
    "c.p1": "Cada hallazgo mientras lees o en diálogo — cada tensión teórica, cada movimiento metodológico, cada hueco — capturado con un clic, clasificado, y archivado exactamente donde corresponde en tu outline.",
    "c.p2": "Para cuando escribes, el argumento ya está tendido. No estás ensamblando — estás componiendo.",
    "c.t1.l": "Teórico",         "c.t1.n": "Una tensión, un marco.",
    "c.t2.l": "Metodológico",    "c.t2.n": "Una manera de mirar.",
    "c.t3.l": "Empírico",        "c.t3.n": "Un hallazgo, un dato.",
    "c.t4.l": "Estructural",     "c.t4.n": "Una forma, un hueco.",
    "c.cat.acc": "Acc. 0042 · Teórico",
    "c.cat.date": "Archivado mar 03:42",
    "c.cat.title": "Ecologías umbrales y comunes ambientales",
    "c.cat.body": "&laquo;Los marcos clásicos de comunes se tambalean ante recursos sin bordes claros — el ruido ambiental, el derrame lumínico, los microclimas como casos paradigmáticos.&raquo;",
    "c.cat.src": "Halbersohn · 2017 · p. 32",
    "c.cat.dest": "§2.1 Umbrales ambientales como común",

    "p.label": "Posición",
    "p.q1": "Discusión con IA,",
    "p.q2": "no escritura con IA.",
    "p.body": "Esto no es autocompletar tu tesis. El sistema desafía tus supuestos, hace preguntas de seguimiento, y te ayuda a pensar con claridad. Tú sigues escribiendo. El argumento sigue siendo tuyo.",
    "p.them.h": "— Otras herramientas",
    "p.them.1": "Generan párrafos sin decirte qué fuentes los respaldan.",
    "p.them.2": "Borran el rastro de tu razonamiento.",
    "p.them.3": "Te dejan con texto que no sabes defender.",
    "p.them.4": "Cada conversación arranca de cero.",
    "p.us.h": "+ Tesyra",
    "p.us.1": "Cristaliza la idea. La archiva donde corresponde.",
    "p.us.2": "Tu argumento toma forma mientras lo construyes — no después.",
    "p.us.3": "Cuando llegas a escribir, la estructura ya existe.",
    "p.us.4": "Cada insight referencia su fuente y su subsección.",

    "a.label": "Acceso",
    "a.d1": "Cada plan,",
    "a.d2": "todos los módulos.",
    "a.lead.1": "Sin restricciones de funciones. Todas las herramientas, desde el primer día.",
    "a.lead.2": " El mejor modelo, en todos los planes.",
    "a.h.col": "Plan",
    "a.t1.name": "Explorer", "a.t1.tag": "— para el primer artículo",
    "a.t2.name": "Researcher", "a.t2.tag": "— para proyectos paralelos",
    "a.t3.name": "Academic Pro", "a.t3.tag": "— para tesis y libros",
    "a.r.price": "Tarifa",
    "a.t1.per": "siempre",
    "a.t2.per": "/ mes",
    "a.t3.per": "/ mes",
    "a.r.credits": "Créditos / mes",
    "a.r.projects": "Proyectos activos",
    "a.r.docs": "Documentos por proyecto",
    "a.r.conv": "Conversaciones por proyecto",
    "a.r.outlines": "Outlines por proyecto",
    "a.r.preassign": "Pre-asignación inteligente",
    "a.r.gaps": "Detección de huecos bibliográficos",
    "a.r.briefing": "Briefing diario",
    "a.r.storage": "Almacenamiento",
    "a.r.included": "incluido", "a.r.included2": "incluido", "a.r.included3": "incluido",
    "a.r.included4": "incluido", "a.r.included5": "incluido", "a.r.included6": "incluido",
    "a.t1.cta": "Empezar gratis",
    "a.t2.cta": "Probar 14 días",
    "a.t3.cta": "Empezar",
    "a.note": "Precios en USD. Cancela cuando quieras. Cobro gestionado por Paddle (merchant of record).",

    "end.l1": "Disfruta pensar.",
    "end.l2": "Todo está ahí.",
    "end.sub": "Empezar es gratis. No necesitas tarjeta.",
    "end.cta1": "Empezar gratis <span class=\"arrow\">→</span>",
    "end.cta2": "Leer el prospecto",

    "fc.about": "Una plataforma para investigadores académicos. De la lectura de fuentes a la escritura del artículo — pensamiento estructurado, asistido.",
    "fc.product": "Producto",
    "fc.method": "El método",
    "fc.crystals": "Cristalizaciones",
    "fc.pricing": "Acceso",
    "fc.position": "Posición",
    "fc.resources": "Recursos",
    "fc.docs": "Documentación",
    "fc.changelog": "Changelog",
    "fc.support": "Soporte",
    "fc.company": "Empresa",
    "fc.about-us": "Sobre Tesyra",
    "fc.contact": "Contacto",
    "fc.press": "Prensa",
    "fc.legal": "Legal",
    "fc.privacy": "Privacidad",
    "fc.terms": "Términos",
    "fc.dpa": "Procesamiento de datos",
    "fc.signoff": "Hecho con cuidado para investigadores"
  }
};
